name: GitHub Actions zip
on: [push]
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: make new directory
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
