name: GitHub Actions zip
on: [push]
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
         

      
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: src/
