name: deploy to lambda
on:
  push:
    branches:
      - main
jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 60
  download_artifact:
    runs-on: ubuntu-latest
    needs: wait
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download
        uses: ./
        with:
          workflow: main.yml
          name: build-artifact
          path: src/
        
      - name: Test
        run: ls
