name: deploy to lambda
on:
  push:
    branches:
      - main
jobs:
  download_artifact:
    runs-on: ubuntu-latest  
      
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          
      - name: Display structure of downloaded files
        run: ls -R
