name: deploy to lambda

on: [push]
 

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 30
  download_artifact:
    runs-on: ubuntu-latest
    needs: wait
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
      - name: Test
        run: ls
 
